### ISSUE TITLE
[BUG]: Incompatability issue

### ISSUE THREAD

**Issue by ZoenkBoenk** [AnOpenSauceDev/FastRandom#36]
### Does an issue already cover this?

- [X] I have searched for any existing issues, and didn't find any.

### Issue description.

I downloaded the faster random mod and I have some other mods, such as lambda is I think I find as the issue, if you guys are able can you try to fix it please?

### Issue replication.

Try downloading the faster random and basically any lambda mod. (I have the lambdynamiclights mod)

### Log File / Crash Report (if applicable)

A mod crashed on startup!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'faster-random'!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.digitalingot.rustextension.ProxiedStart.main(ProxiedStart.java:16)
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'faster-random'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160)
	... 7 more
Caused by: java.lang.ExceptionInInitializerError
	at com.github.anopensaucedev.fasterrandom.FasterRandomPrelaunch.onPreLaunch(FasterRandomPrelaunch.java:18)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	... 8 more
Caused by: java.lang.IllegalArgumentException: No implementation of the random number generator algorithm "L64X128MixRandom" is available
	at java.base/java.util.random.RandomGeneratorFactory.findProvider(Unknown Source)
	at java.base/java.util.random.RandomGeneratorFactory.factoryOf(Unknown Source)
	at java.base/java.util.random.RandomGeneratorFactory.of(Unknown Source)
	at com.github.anopensaucedev.fasterrandom.FasterRandom.<clinit>(FasterRandom.java:21)
	... 10 more

**Comment by ZoenkBoenk** [comment]
Nvm, it works all fine the incompatability seems to be with feather client, hope y'all are able to fix it

**Comment by Steveplays28** [comment]
You need to use a JRE/JDK that supports the optimisations, as stated in the readme.
Try giving Feather Client a different JRE/JDK if possible.
